
/*
Customer Shopping Behavior Analysis
Converted from PostgreSQL → MySQL
Table name used: shopping_data
Database: customer_behavior

Each question includes explanation comments.
*/

-- =========================================================
-- Q1. What is the total revenue generated by male vs. female customers?
-- Explanation:
-- This query groups customers by gender and calculates the total revenue
-- generated by each group using SUM(purchase_amount).
-- Business insight: Helps understand which gender contributes more revenue.
-- =========================================================

SELECT 
    gender,
    SUM(purchase_amount) AS total_revenue
FROM shopping_data
GROUP BY gender;


-- =========================================================
-- Q2. Which customers used a discount but still spent more than the average purchase amount?
-- Explanation:
-- First we calculate the overall average purchase amount.
-- Then we select customers who used discounts but spent equal to or above the average.
-- Business insight: Identifies high-value customers even when discounts are applied.
-- =========================================================

SELECT 
    customer_id,
    purchase_amount
FROM shopping_data
WHERE discount_applied = 'Yes'
AND purchase_amount >= (
    SELECT AVG(purchase_amount)
    FROM shopping_data
);


-- =========================================================
-- Q3. Which are the top 5 products with the highest average review rating?
-- Explanation:
-- Groups by product and calculates the average review rating.
-- Results are sorted from highest to lowest and limited to the top 5.
-- Business insight: Helps identify the most positively reviewed products.
-- =========================================================

SELECT 
    item_purchased,
    ROUND(AVG(review_rating),2) AS avg_product_rating
FROM shopping_data
GROUP BY item_purchased
ORDER BY avg_product_rating DESC
LIMIT 5;


-- =========================================================
-- Q4. Compare the average purchase amount between Standard and Express shipping.
-- Explanation:
-- Calculates the average purchase amount for each shipping type.
-- Only includes Standard and Express shipping options.
-- Business insight: Determines if customers choosing faster shipping spend more.
-- =========================================================

SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount),2) AS avg_purchase_amount
FROM shopping_data
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;


-- =========================================================
-- Q5. Do subscribed customers spend more?
-- Explanation:
-- Compares subscribers and non-subscribers based on:
-- total number of customers
-- average purchase amount
-- total revenue generated.
-- Business insight: Shows whether subscription programs increase spending.
-- =========================================================

SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount),2) AS avg_spend,
    ROUND(SUM(purchase_amount),2) AS total_revenue
FROM shopping_data
GROUP BY subscription_status
ORDER BY total_revenue DESC;


-- =========================================================
-- Q6. Which products have the highest percentage of purchases with discounts applied?
-- Explanation:
-- Calculates the percentage of purchases where discounts were used for each product.
-- Business insight: Identifies products most dependent on discounts for sales.
-- =========================================================

SELECT 
    item_purchased,
    ROUND(
        100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS discount_rate_percentage
FROM shopping_data
GROUP BY item_purchased
ORDER BY discount_rate_percentage DESC
LIMIT 5;


-- =========================================================
-- Q7. Segment customers into New, Returning, and Loyal customers.
-- Explanation:
-- Uses previous_purchases to classify customers into segments.
-- Business insight: Helps understand customer loyalty distribution.
-- =========================================================

WITH customer_segments AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New Customer'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning Customer'
            ELSE 'Loyal Customer'
        END AS customer_segment
    FROM shopping_data
)

SELECT 
    customer_segment,
    COUNT(*) AS number_of_customers
FROM customer_segments
GROUP BY customer_segment;


-- =========================================================
-- Q8. What are the top 3 most purchased products within each category?
-- Explanation:
-- Uses window function ROW_NUMBER to rank products by number of orders within each category.
-- Business insight: Identifies the best-selling items in each category.
-- =========================================================

WITH product_rankings AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS rank_in_category
    FROM shopping_data
    GROUP BY category, item_purchased
)

SELECT 
    category,
    item_purchased,
    total_orders,
    rank_in_category
FROM product_rankings
WHERE rank_in_category <= 3;


-- =========================================================
-- Q9. Are repeat buyers (more than 5 previous purchases) more likely to subscribe?
-- Explanation:
-- Filters customers with more than 5 previous purchases
-- then groups them by subscription status.
-- Business insight: Shows whether loyal buyers tend to subscribe.
-- =========================================================

SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM shopping_data
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- =========================================================
-- Q10. What is the revenue contribution of each age group?
-- Explanation:
-- Groups customers by age group and calculates total revenue.
-- Business insight: Helps identify which age segments generate the most sales.
-- =========================================================

SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM shopping_data
GROUP BY age_group
ORDER BY total_revenue DESC;

